obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_ARCH_MSM)		+= qcom/
obj-$(CONFIG_BATTERY_CW2015)	+= cw2015_battery.o ### add for c3
obj-$(CONFIG_CHARGER_BQ2560) += bq2560x_charger.o
obj-$(CONFIG_GAUGE_BQ27426) += bq27426_fg.o
